from materialprices import MaterialPriceViewSet
from materials import MaterialsViewSet
from playerinventories import PlayerInventoryViewSet
from playerstatuses import PlayerStatusViewSet
from towns import TownViewSet
from users import UserViewSet